name: Update mirror hashes in Makefile.apk
permissions:
  contents: write
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git xz-utils

      - name: Extract variables from Makefile.apk
        run: |
          PKG_SOURCE_URL=$(grep '^PKG_SOURCE_URL:=' Makefile.apk | sed 's/PKG_SOURCE_URL:=//')
          PKG_SOURCE_VERSION=$(grep '^PKG_SOURCE_VERSION:=' Makefile.apk | sed 's/PKG_SOURCE_VERSION:=//')
          SMARTDNS_WEBUI_SOURCE_URL=$(grep '^SMARTDNS_WEBUI_SOURCE_URL:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_SOURCE_URL:=//')
          SMARTDNS_WEBUI_SOURCE_VERSION=$(grep '^SMARTDNS_WEBUI_SOURCE_VERSION:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_SOURCE_VERSION:=//')
          PKG_NAME=$(grep '^PKG_NAME:=' Makefile.apk | sed 's/PKG_NAME:=//')
          PKG_VERSION=$(grep '^PKG_VERSION:=' Makefile.apk | sed 's/PKG_VERSION:=//')
          SMARTDNS_WEBUI_VERSION=$(grep '^SMARTDNS_WEBUI_VERSION:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_VERSION:=//')
          SMARTDNS_WEBUI_FILE=$(grep '^SMARTDNS_WEBUI_FILE:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_FILE:=//')
          echo "PKG_SOURCE_URL=$PKG_SOURCE_URL" >> $GITHUB_ENV
          echo "PKG_SOURCE_VERSION=$PKG_SOURCE_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_SOURCE_URL=$SMARTDNS_WEBUI_SOURCE_URL" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_SOURCE_VERSION=$SMARTDNS_WEBUI_SOURCE_VERSION" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_VERSION=$SMARTDNS_WEBUI_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_FILE=$SMARTDNS_WEBUI_FILE" >> $GITHUB_ENV

      - name: Calculate PKG_MIRROR_HASH for smartdns
        run: |
          # Clone smartdns repository
          git clone "${PKG_SOURCE_URL}" smartdns
          cd smartdns
          git checkout "${PKG_SOURCE_VERSION}"
          git submodule update --init --recursive
          
          # Get timestamp from git commit
          export TAR_TIMESTAMP=$(git log -1 --format='@%ct')
          
          # Remove .git directory
          rm -rf .git .gitmodules
          
          # Create tar.xz archive with OpenWrt-specific options
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name \
            ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c . | xz -zc -7e > "../${PKG_NAME}-${PKG_VERSION}.tar.xz"
          
          # Calculate SHA256 hash
          PKG_MIRROR_HASH=$(sha256sum "../${PKG_NAME}-${PKG_VERSION}.tar.xz" | cut -d ' ' -f1)
          echo "PKG_MIRROR_HASH=$PKG_MIRROR_HASH" >> $GITHUB_ENV
          
          # Clean up
          cd ..
          rm -rf smartdns "${PKG_NAME}-${PKG_VERSION}.tar.xz"

      - name: Calculate MIRROR_HASH for smartdns-webui
        run: |
          # Clone smartdns-webui repository
          git clone "${SMARTDNS_WEBUI_SOURCE_URL}" smartdns-webui
          cd smartdns-webui
          git checkout "${SMARTDNS_WEBUI_SOURCE_VERSION}"
          git submodule update --init --recursive
          
          # Get timestamp from git commit
          export TAR_TIMESTAMP=$(git log -1 --format='@%ct')
          
          # Remove .git directory
          rm -rf .git .gitmodules
          
          # Create tar.gz archive with OpenWrt-specific options
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name \
            ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c . | gzip -nc > "../${SMARTDNS_WEBUI_FILE}"
          
          # Calculate SHA256 hash
          WEBUI_MIRROR_HASH=$(sha256sum "../${SMARTDNS_WEBUI_FILE}" | cut -d ' ' -f1)
          echo "WEBUI_MIRROR_HASH=$WEBUI_MIRROR_HASH" >> $GITHUB_ENV
          
          # Clean up
          cd ..
          rm -rf smartdns-webui "${SMARTDNS_WEBUI_FILE}"

      - name: Update Makefile.apk
        run: |
          # Update PKG_MIRROR_HASH
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$PKG_MIRROR_HASH/" Makefile.apk
          
          # Update MIRROR_HASH in Download/smartdns-webui section
          sed -i "/define Download\/smartdns-webui/,/endef/ s/MIRROR_HASH :=.*/MIRROR_HASH := $WEBUI_MIRROR_HASH/" Makefile.apk

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Makefile.apk
          git commit -m "chore: update PKG_MIRROR_HASH and webui MIRROR_HASH" || exit 0
          for i in {1..3}; do
            git push origin HEAD:${{ github.ref_name }} && break
            echo "Push failed, retrying ($i/3)"
            sleep 5
          done || { echo "Failed to push after 3 attempts"; exit 1; }
