name: Update mirror hashes in Makefile.apk
permissions:
  contents: write
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git xz-utils

      - name: Extract variables from Makefile.apk
        run: |
          PKG_SOURCE_URL=$(grep '^PKG_SOURCE_URL:=' Makefile.apk | sed 's/PKG_SOURCE_URL:=//')
          PKG_SOURCE_VERSION=$(grep '^PKG_SOURCE_VERSION:=' Makefile.apk | sed 's/PKG_SOURCE_VERSION:=//')
          SMARTDNS_WEBUI_SOURCE_URL=$(grep '^SMARTDNS_WEBUI_SOURCE_URL:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_SOURCE_URL:=//')
          SMARTDNS_WEBUI_SOURCE_VERSION=$(grep '^SMARTDNS_WEBUI_SOURCE_VERSION:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_SOURCE_VERSION:=//')
          PKG_NAME=$(grep '^PKG_NAME:=' Makefile.apk | sed 's/PKG_NAME:=//')
          PKG_VERSION=$(grep '^PKG_VERSION:=' Makefile.apk | sed 's/PKG_VERSION:=//')
          SMARTDNS_WEBUI_VERSION=$(grep '^SMARTDNS_WEBUI_VERSION:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_VERSION:=//')
          SMARTDNS_WEBUI_FILE=$(grep '^SMARTDNS_WEBUI_FILE:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_FILE:=//')
          SMARTDNS_SUBDIR="${PKG_NAME}-${PKG_VERSION}"
          WEBUI_SUBDIR="smartdns-webui"
          [ -n "$PKG_SOURCE_URL" ] || { echo "Error: PKG_SOURCE_URL not found"; exit 1; }
          [ -n "$PKG_SOURCE_VERSION" ] || { echo "Error: PKG_SOURCE_VERSION not found"; exit 1; }
          [ -n "$SMARTDNS_WEBUI_SOURCE_URL" ] || { echo "Error: SMARTDNS_WEBUI_SOURCE_URL not found"; exit 1; }
          [ -n "$SMARTDNS_WEBUI_SOURCE_VERSION" ] || { echo "Error: SMARTDNS_WEBUI_SOURCE_VERSION not found"; exit 1; }
          [ -n "$PKG_NAME" ] || { echo "Error: PKG_NAME not found"; exit 1; }
          [ -n "$PKG_VERSION" ] || { echo "Error: PKG_VERSION not found"; exit 1; }
          [ -n "$SMARTDNS_WEBUI_VERSION" ] || { echo "Error: SMARTDNS_WEBUI_VERSION not found"; exit 1; }
          [ -n "$SMARTDNS_WEBUI_FILE" ] || { echo "Error: SMARTDNS_WEBUI_FILE not found"; exit 1; }
          echo "Extracted variables:"
          echo "PKG_SOURCE_URL=$PKG_SOURCE_URL"
          echo "PKG_SOURCE_VERSION=$PKG_SOURCE_VERSION"
          echo "SMARTDNS_WEBUI_SOURCE_URL=$SMARTDNS_WEBUI_SOURCE_URL"
          echo "SMARTDNS_WEBUI_SOURCE_VERSION=$SMARTDNS_WEBUI_SOURCE_VERSION"
          echo "PKG_NAME=$PKG_NAME"
          echo "PKG_VERSION=$PKG_VERSION"
          echo "SMARTDNS_WEBUI_VERSION=$SMARTDNS_WEBUI_VERSION"
          echo "SMARTDNS_WEBUI_FILE=$SMARTDNS_WEBUI_FILE"
          echo "SMARTDNS_SUBDIR=$SMARTDNS_SUBDIR"
          echo "WEBUI_SUBDIR=$WEBUI_SUBDIR"
          echo "PKG_SOURCE_URL=$PKG_SOURCE_URL" >> $GITHUB_ENV
          echo "PKG_SOURCE_VERSION=$PKG_SOURCE_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_SOURCE_URL=$SMARTDNS_WEBUI_SOURCE_URL" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_SOURCE_VERSION=$SMARTDNS_WEBUI_SOURCE_VERSION" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_VERSION=$SMARTDNS_WEBUI_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_FILE=$SMARTDNS_WEBUI_FILE" >> $GITHUB_ENV
          echo "SMARTDNS_SUBDIR=$SMARTDNS_SUBDIR" >> $GITHUB_ENV
          echo "WEBUI_SUBDIR=$WEBUI_SUBDIR" >> $GITHUB_ENV

      - name: Calculate PKG_MIRROR_HASH for smartdns
        run: |
          # Create temporary directories
          mkdir -p tmp/dl
          
          # Clone smartdns repository
          git clone "${PKG_SOURCE_URL}" "tmp/dl/${SMARTDNS_SUBDIR}" || { echo "Error: Failed to clone ${PKG_SOURCE_URL}"; exit 1; }
          cd "tmp/dl/${SMARTDNS_SUBDIR}"
          git checkout "${PKG_SOURCE_VERSION}" || { echo "Error: Failed to checkout ${PKG_SOURCE_VERSION}"; exit 1; }
          git config core.abbrev 8
          
          # Get timestamp from git commit
          export TAR_TIMESTAMP=$(git log -1 --format='@%ct') || { echo "Error: Failed to get commit timestamp"; exit 1; }
          
          # Create git archive
          git archive --format=tar HEAD --output=../../"${SMARTDNS_SUBDIR}".tar.git || { echo "Error: Failed to create git archive"; exit 1; }
          
          # Append .git and .gitmodules (if they exist)
          tar --numeric-owner --owner=0 --group=0 --ignore-failed-read -C . -f ../../"${SMARTDNS_SUBDIR}".tar.git -r .git .gitmodules 2>/dev/null
          
          # Extract archive and update submodules
          cd ../..
          rm -rf "tmp/dl/${SMARTDNS_SUBDIR}"
          mkdir -p "tmp/dl/${SMARTDNS_SUBDIR}"
          tar -C "tmp/dl/${SMARTDNS_SUBDIR}" -xf "tmp/dl/${SMARTDNS_SUBDIR}".tar.git || { echo "Error: Failed to extract git archive"; exit 1; }
          cd "tmp/dl/${SMARTDNS_SUBDIR}"
          git submodule update --init --recursive || true
          rm -rf .git .gitmodules
          
          # Create final tar.xz archive with subdirectory
          cd ..
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name \
            ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c "${SMARTDNS_SUBDIR}" | xz -zc -7e > "../${SMARTDNS_SUBDIR}.tar.xz" || { echo "Error: Failed to create tar.xz archive"; exit 1; }
          
          # Calculate SHA256 hash
          PKG_MIRROR_HASH=$(sha256sum "../${SMARTDNS_SUBDIR}.tar.xz" | cut -d ' ' -f1) || { echo "Error: Failed to calculate SHA256 hash"; exit 1; }
          echo "Calculated PKG_MIRROR_HASH=$PKG_MIRROR_HASH"
          echo "PKG_MIRROR_HASH=$PKG_MIRROR_HASH" >> $GITHUB_ENV
          
          # Clean up
          rm -rf tmp/dl "../${SMARTDNS_SUBDIR}.tar.xz"

      - name: Calculate MIRROR_HASH for smartdns-webui
        run: |
          # Create temporary directories
          mkdir -p tmp/dl
          
          # Clone smartdns-webui repository
          git clone "${SMARTDNS_WEBUI_SOURCE_URL}" "tmp/dl/${WEBUI_SUBDIR}" || { echo "Error: Failed to clone ${SMARTDNS_WEBUI_SOURCE_URL}"; exit 1; }
          cd "tmp/dl/${WEBUI_SUBDIR}"
          git checkout "${SMARTDNS_WEBUI_SOURCE_VERSION}" || { echo "Error: Failed to checkout ${SMARTDNS_WEBUI_SOURCE_VERSION}"; exit 1; }
          git config core.abbrev 8
          
          # Get timestamp from git commit
          export TAR_TIMESTAMP=$(git log -1 --format='@%ct') || { echo "Error: Failed to get commit timestamp"; exit 1; }
          
          # Create git archive
          git archive --format=tar HEAD --output=../../"${WEBUI_SUBDIR}".tar.git || { echo "Error: Failed to create git archive"; exit 1; }
          
          # Append .git and .gitmodules (if they exist)
          tar --numeric-owner --owner=0 --group=0 --ignore-failed-read -C . -f ../../"${WEBUI_SUBDIR}".tar.git -r .git .gitmodules 2>/dev/null
          
          # Extract archive and update submodules
          cd ../..
          rm -rf "tmp/dl/${WEBUI_SUBDIR}"
          mkdir -p "tmp/dl/${WEBUI_SUBDIR}"
          tar -C "tmp/dl/${WEBUI_SUBDIR}" -xf "tmp/dl/${WEBUI_SUBDIR}".tar.git || { echo "Error: Failed to extract git archive"; exit 1; }
          cd "tmp/dl/${WEBUI_SUBDIR}"
          git submodule update --init --recursive || true
          rm -rf .git .gitmodules
          
          # Create final tar.gz archive with subdirectory
          cd ..
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name \
            ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c "${WEBUI_SUBDIR}" | gzip -nc > "../${SMARTDNS_WEBUI_FILE}" || { echo "Error: Failed to create tar.gz archive"; exit 1; }
          
          # Calculate SHA256 hash
          WEBUI_MIRROR_HASH=$(sha256sum "../${SMARTDNS_WEBUI_FILE}" | cut -d ' ' -f1) || { echo "Error: Failed to calculate SHA256 hash"; exit 1; }
          echo "Calculated WEBUI_MIRROR_HASH=$WEBUI_MIRROR_HASH"
          echo "WEBUI_MIRROR_HASH=$WEBUI_MIRROR_HASH" >> $GITHUB_ENV
          
          # Clean up
          rm -rf tmp/dl "../${SMARTDNS_WEBUI_FILE}"

      - name: Update Makefile.apk
        run: |
          # Update PKG_MIRROR_HASH
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$PKG_MIRROR_HASH/" Makefile.apk
          
          # Update MIRROR_HASH in Download/smartdns-webui section
          sed -i "/define Download\/smartdns-webui/,/endef/ s/MIRROR_HASH :=.*/MIRROR_HASH := $WEBUI_MIRROR_HASH/" Makefile.apk

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Makefile.apk
          git commit -m "chore: update PKG_MIRROR_HASH and webui MIRROR_HASH" || exit 0
          for i in {1..3}; do
            git push origin HEAD:${{ github.ref_name }} && break
            echo "Push failed, retrying ($i/3)"
            sleep 5
          done || { echo "Failed to push after 3 attempts"; exit 1; }
