name: Update mirror hashes in Makefile.apk
permissions:
  contents: write
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git xz-utils

      - name: Extract variables from Makefile.apk
        run: |
          PKG_SOURCE_URL=$(grep '^PKG_SOURCE_URL:=' Makefile.apk | sed 's/PKG_SOURCE_URL:=//')
          PKG_SOURCE_VERSION=$(grep '^PKG_SOURCE_VERSION:=' Makefile.apk | sed 's/PKG_SOURCE_VERSION:=//')
          SMARTDNS_WEBUI_SOURCE_URL=$(grep '^SMARTDNS_WEBUI_SOURCE_URL:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_SOURCE_URL:=//')
          SMARTDNS_WEBUI_SOURCE_VERSION=$(grep '^SMARTDNS_WEBUI_SOURCE_VERSION:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_SOURCE_VERSION:=//')
          PKG_NAME=$(grep '^PKG_NAME:=' Makefile.apk | sed 's/PKG_NAME:=//')
          PKG_VERSION=$(grep '^PKG_VERSION:=' Makefile.apk | sed 's/PKG_VERSION:=//')
          SMARTDNS_WEBUI_VERSION=$(grep '^SMARTDNS_WEBUI_VERSION:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_VERSION:=//')
          SMARTDNS_WEBUI_FILE=$(grep '^SMARTDNS_WEBUI_FILE:=' Makefile.apk | sed 's/SMARTDNS_WEBUI_FILE:=//')
          echo "PKG_SOURCE_URL=$PKG_SOURCE_URL" >> $GITHUB_ENV
          echo "PKG_SOURCE_VERSION=$PKG_SOURCE_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_SOURCE_URL=$SMARTDNS_WEBUI_SOURCE_URL" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_SOURCE_VERSION=$SMARTDNS_WEBUI_SOURCE_VERSION" >> $GITHUB_ENV
          echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
          echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_VERSION=$SMARTDNS_WEBUI_VERSION" >> $GITHUB_ENV
          echo "SMARTDNS_WEBUI_FILE=$SMARTDNS_WEBUI_FILE" >> $GITHUB_ENV

      - name: Calculate PKG_MIRROR_HASH for smartdns
        run: |
          # Create temporary directory
          mkdir -p tmp/dl
          
          # Set subdir for smartdns
          SMARTDNS_SUBDIR="${PKG_NAME}-${PKG_VERSION}"
          
          # Clone into subdir
          cd tmp/dl
          git clone "${PKG_SOURCE_URL}" "${SMARTDNS_SUBDIR}"
          cd "${SMARTDNS_SUBDIR}"
          git checkout "${PKG_SOURCE_VERSION}"
          export TAR_TIMESTAMP=$(git log -1 --format='@%ct')
          git config core.abbrev 8
          git archive --format=tar HEAD --output=../../"${SMARTDNS_SUBDIR}".tar.git
          tar --numeric-owner --owner=0 --group=0 --ignore-failed-read -C . -f ../../"${SMARTDNS_SUBDIR}".tar.git -r .git .gitmodules 2>/dev/null
          cd ../..
          rm -rf tmp/dl/"${SMARTDNS_SUBDIR}"
          mkdir tmp/dl/"${SMARTDNS_SUBDIR}"
          tar -C tmp/dl/"${SMARTDNS_SUBDIR}" -xf tmp/dl/"${SMARTDNS_SUBDIR}".tar.git
          cd tmp/dl/"${SMARTDNS_SUBDIR}"
          git submodule update --init --recursive || true  # Ignore if no submodules
          rm -rf .git .gitmodules
          cd ..
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name \
            ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c "${SMARTDNS_SUBDIR}" | xz -zc -7e > "../${SMARTDNS_SUBDIR}.tar.xz"
          
          # Calculate SHA256 hash
          PKG_MIRROR_HASH=$(sha256sum "../${SMARTDNS_SUBDIR}.tar.xz" | cut -d ' ' -f1)
          echo "PKG_MIRROR_HASH=$PKG_MIRROR_HASH" >> $GITHUB_ENV
          
          # Clean up
          rm -rf tmp/dl "${SMARTDNS_SUBDIR}.tar.xz"

      - name: Calculate MIRROR_HASH for smartdns-webui
        run: |
          # Create temporary directory
          mkdir -p tmp/dl
          
          # Set subdir for smartdns-webui
          WEBUI_SUBDIR="smartdns-webui"
          
          # Clone into subdir
          cd tmp/dl
          git clone "${SMARTDNS_WEBUI_SOURCE_URL}" "${WEBUI_SUBDIR}"
          cd "${WEBUI_SUBDIR}"
          git checkout "${SMARTDNS_WEBUI_SOURCE_VERSION}"
          export TAR_TIMESTAMP=$(git log -1 --format='@%ct')
          git config core.abbrev 8
          git archive --format=tar HEAD --output=../../"${WEBUI_SUBDIR}".tar.git
          tar --numeric-owner --owner=0 --group=0 --ignore-failed-read -C . -f ../../"${WEBUI_SUBDIR}".tar.git -r .git .gitmodules 2>/dev/null
          cd ../..
          rm -rf tmp/dl/"${WEBUI_SUBDIR}"
          mkdir tmp/dl/"${WEBUI_SUBDIR}"
          tar -C tmp/dl/"${WEBUI_SUBDIR}" -xf tmp/dl/"${WEBUI_SUBDIR}".tar.git
          cd tmp/dl/"${WEBUI_SUBDIR}"
          git submodule update --init --recursive || true  # Ignore if no submodules
          rm -rf .git .gitmodules
          cd ..
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name \
            ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c "${WEBUI_SUBDIR}" | gzip -nc > "../${SMARTDNS_WEBUI_FILE}"
          
          # Calculate SHA256 hash
          WEBUI_MIRROR_HASH=$(sha256sum "../${SMARTDNS_WEBUI_FILE}" | cut -d ' ' -f1)
          echo "WEBUI_MIRROR_HASH=$WEBUI_MIRROR_HASH" >> $GITHUB_ENV
          
          # Clean up
          rm -rf tmp/dl "${SMARTDNS_WEBUI_FILE}"

      - name: Update Makefile.apk
        run: |
          # Update PKG_MIRROR_HASH
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$PKG_MIRROR_HASH/" Makefile.apk
          
          # Update MIRROR_HASH in Download/smartdns-webui section
          sed -i "/define Download\/smartdns-webui/,/endef/ s/MIRROR_HASH :=.*/MIRROR_HASH := $WEBUI_MIRROR_HASH/" Makefile.apk

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Makefile.apk
          git commit -m "chore: update PKG_MIRROR_HASH and webui MIRROR_HASH" || exit 0
          for i in {1..3}; do
            git push origin HEAD:${{ github.ref_name }} && break
            echo "Push failed, retrying ($i/3)"
            sleep 5
          done || { echo "Failed to push after 3 attempts"; exit 1; }
