name: Update mirror hashes in Makefile.apk

permissions:
  contents: write

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  update-hashes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (use PAT to allow downstream workflows)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_WORKFLOW }}   # 需在仓库 Secrets 配置 PAT_WORKFLOW（含 repo+workflow）

      - name: Install needed tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq xz-utils git rsync file

      - name: Parse variables from Makefile.apk (robust)
        id: parse
        run: |
          set -euo pipefail
          MF=Makefile.apk
          [ -f "$MF" ] || { echo "Makefile.apk not found"; exit 1; }

          # 兼容 CRLF
          if file "$MF" | grep -qi 'CRLF'; then
            sed -i 's/\r$//' "$MF"
          fi

          # 支持  =  :=  ?=  +=；忽略前导空白；截断行尾注释；去掉包裹引号
          get_val() {
            local key="$1"
            sed -nE "s|^[[:space:]]*${key}[[:space:]]*(:|\\+|\\?)?=[[:space:]]*([^#]*)[[:space:]]*.*$|\\2|p" "$MF" | head -n1 \
            | sed -E 's/^[[:space:]]+|[[:space:]]+$//g; s/^\"(.*)\"$/\1/; s/^\x27(.*)\x27$/\1/'
          }

          PKG_NAME="$(get_val 'PKG_NAME')"
          PKG_VERSION="$(get_val 'PKG_VERSION')"
          PKG_SOURCE_PROTO="$(get_val 'PKG_SOURCE_PROTO')"
          PKG_SOURCE_URL="$(get_val 'PKG_SOURCE_URL')"
          PKG_SOURCE_VERSION="$(get_val 'PKG_SOURCE_VERSION')"

          WEBUI_VERSION="$(get_val 'SMARTDNS_WEBUI_VERSION')"
          WEBUI_SOURCE_PROTO="$(get_val 'SMARTDNS_WEBUI_SOURCE_PROTO')"
          WEBUI_SOURCE_URL="$(get_val 'SMARTDNS_WEBUI_SOURCE_URL')"
          WEBUI_SOURCE_VERSION="$(get_val 'SMARTDNS_WEBUI_SOURCE_VERSION')"
          WEBUI_FILE="$(get_val 'SMARTDNS_WEBUI_FILE')"

          {
            echo "pkg_name=$PKG_NAME"
            echo "pkg_ver=$PKG_VERSION"
            echo "pkg_proto=$PKG_SOURCE_PROTO"
            echo "pkg_url=$PKG_SOURCE_URL"
            echo "pkg_commit=$PKG_SOURCE_VERSION"
            echo "webui_ver=$WEBUI_VERSION"
            echo "webui_proto=$WEBUI_SOURCE_PROTO"
            echo "webui_url=$WEBUI_SOURCE_URL"
            echo "webui_commit=$WEBUI_SOURCE_VERSION"
            echo "webui_file=$WEBUI_FILE"
          } >> "$GITHUB_OUTPUT"

          echo "::group::Parsed values"
          awk -v k1="PKG_SOURCE_PROTO" -v k2="SMARTDNS_WEBUI_SOURCE_PROTO" '
            $0 ~ k1 || $0 ~ k2 { print NR ":" $0 }
          ' "$MF" || true
          echo "PKG_SOURCE_PROTO=${PKG_SOURCE_PROTO}"
          echo "SMARTDNS_WEBUI_SOURCE_PROTO=${WEBUI_SOURCE_PROTO}"
          echo "::endgroup::"

      - name: Normalize repo URLs (https scheme, GitHub)
        id: norm
        run: |
          set -euo pipefail
          norm() {
            local u="$1"
            # //github.com/owner/repo.git  -> https://github.com/owner/repo.git
            if echo "$u" | grep -qE '^//github\.com/'; then
              u="https:${u}"
            fi
            # git@github.com:owner/repo.git -> https://github.com/owner/repo.git
            if echo "$u" | grep -qE '^git@github\.com:'; then
              u="https://github.com/$(echo "$u" | sed -E 's#^git@github\.com:##')"
            fi
            # github.com/owner/repo.git -> https://github.com/owner/repo.git
            if echo "$u" | grep -qE '^github\.com/'; then
              u="https://$u"
            fi
            echo "$u"
          }

          PKG_URL="$(norm '${{ steps.parse.outputs.pkg_url }}')"
          WEBUI_URL="$(norm '${{ steps.parse.outputs.webui_url }}')"

          echo "pkg_url_norm=$PKG_URL"     >> "$GITHUB_OUTPUT"
          echo "webui_url_norm=$WEBUI_URL" >> "$GITHUB_OUTPUT"

          echo "Normalized PKG URL : $PKG_URL"
          echo "Normalized WEBUI URL: $WEBUI_URL"

      - name: Compute PKG_MIRROR_HASH (respect PKG_SOURCE_PROTO)
        id: hash_pkg
        run: |
          set -euo pipefail
          PROTO='${{ steps.parse.outputs.pkg_proto }}'
          REPO='${{ steps.norm.outputs.pkg_url_norm }}'
          COMMIT='${{ steps.parse.outputs.pkg_commit }}'
          NAME='${{ steps.parse.outputs.pkg_name }}'
          VER='${{ steps.parse.outputs.pkg_ver }}'

          [ -n "$PROTO" ]  || { echo "PKG_SOURCE_PROTO empty"; exit 1; }
          [ -n "$REPO" ]   || { echo "PKG_SOURCE_URL empty"; exit 1; }
          [ -n "$COMMIT" ] || { echo "PKG_SOURCE_VERSION empty"; exit 1; }

          if [ "$PROTO" != "git" ]; then
            echo "Unsupported PKG_SOURCE_PROTO=$PROTO (only git implemented)"; exit 2
          fi

          git config --global core.autocrlf false
          rm -rf pkg_repo pkg_stage pkg_tree.tar && mkdir -p pkg_stage
          git clone --no-tags --filter=tree:0 "$REPO" pkg_repo
          git -C pkg_repo fetch origin "$COMMIT" --depth=1
          git -C pkg_repo checkout "$COMMIT"

          TS=$(git -C pkg_repo log -1 --format=%ct)
          PREFIX="${NAME}-${VER}/"

          git -C pkg_repo archive --format=tar --prefix="$PREFIX" "$COMMIT" -o pkg_tree.tar
          tar -C pkg_stage -xf pkg_tree.tar

          if [ -f pkg_repo/.gitmodules ]; then
            git -C pkg_repo submodule update --init --recursive
            while IFS= read -r name; do
              [ -z "$name" ] && continue
              path=$(git -C pkg_repo config --file .gitmodules "submodule.${name}.path" || true)
              [ -z "$path" ] && continue
              dst="pkg_stage/${PREFIX}${path}"
              mkdir -p "$dst"
              rsync -a --delete --exclude '.git' --exclude '.gitmodules' "pkg_repo/${path}/" "$dst/"
            done < <(git -C pkg_repo config --file .gitmodules --name-only --get-regexp 'submodule\..*\.path' \
                    | sed -E 's/^submodule\.(.+)\.path$/\1/')
          fi

          OUT="source-${NAME}-${VER}-${COMMIT}.tar.xz"
          tar --numeric-owner --owner=0 --group=0 --mode=a-s \
              --sort=name --mtime="@${TS}" \
              -C pkg_stage -c "${PREFIX%/}" | xz -zc -7e > "$OUT"

          SHA_PKG=$(sha256sum "$OUT" | awk '{print $1}')
          echo "sha_pkg=$SHA_PKG" >> "$GITHUB_OUTPUT"
          echo "PKG_MIRROR_HASH: $SHA_PKG"

      - name: Compute MIRROR_HASH for smartdns-webui (respect *_SOURCE_PROTO)
        id: hash_webui
        run: |
          set -euo pipefail
          PROTO='${{ steps.parse.outputs.webui_proto }}'
          REPO='${{ steps.norm.outputs.webui_url_norm }}'
          COMMIT='${{ steps.parse.outputs.webui_commit }}'
          VER='${{ steps.parse.outputs.webui_ver }}'
          FILE='${{ steps.parse.outputs.webui_file }}'

          [ -n "$PROTO" ]  || { echo "SMARTDNS_WEBUI_SOURCE_PROTO empty"; exit 1; }
          [ -n "$REPO" ]   || { echo "SMARTDNS_WEBUI_SOURCE_URL empty"; exit 1; }
          [ -n "$COMMIT" ] || { echo "SMARTDNS_WEBUI_SOURCE_VERSION empty"; exit 1; }

          if [ "$PROTO" != "git" ]; then
            echo "Unsupported WEBUI PROTO=$PROTO (only git implemented)"; exit 2
          fi

          git config --global core.autocrlf false
          rm -rf webui_repo webui_stage webui_tree.tar && mkdir -p webui_stage
          git clone --no-tags --filter=tree:0 "$REPO" webui_repo
          git -C webui_repo fetch origin "$COMMIT" --depth=1
          git -C webui_repo checkout "$COMMIT"

          TS=$(git -C webui_repo log -1 --format=%ct)
          PREFIX="smartdns-webui-${VER}/"

          git -C webui_repo archive --format=tar --prefix="$PREFIX" "$COMMIT" -o webui_tree.tar
          tar -C webui_stage -xf webui_tree.tar

          if [ -f webui_repo/.gitmodules ]; then
            git -C webui_repo submodule update --init --recursive
            while IFS= read -r name; do
              [ -z "$name" ] && continue
              path=$(git -C webui_repo config --file .gitmodules "submodule.${name}.path" || true)
              [ -z "$path" ] && continue
              dst="webui_stage/${PREFIX}${path}"
              mkdir -p "$dst"
              rsync -a --delete --exclude '.git' --exclude '.gitmodules' "webui_repo/${path}/" "$dst/"
            done < <(git -C webui_repo config --file .gitmodules --name-only --get-regexp 'submodule\..*\.path' \
                    | sed -E 's/^submodule\.(.+)\.path$/\1/')
          fi

          OUT="${FILE:-smartdns-webui-${VER}.tar.gz}"
          tar --numeric-owner --owner=0 --group=0 --mode=a-s \
              --sort=name --mtime="@${TS}" \
              -C webui_stage -c "${PREFIX%/}" | gzip -n > "$OUT"

          SHA_WEBUI=$(sha256sum "$OUT" | awk '{print $1}')
          echo "sha_webui=$SHA_WEBUI" >> "$GITHUB_OUTPUT"
          echo "WEBUI MIRROR_HASH: $SHA_WEBUI"

      - name: Update Makefile.apk with new hashes
        id: patch
        run: |
          set -euo pipefail
          MF=Makefile.apk
          SHA_PKG='${{ steps.hash_pkg.outputs.sha_pkg }}'
          SHA_WEBUI='${{ steps.hash_webui.outputs.sha_webui }}'

          # 先统一写法：把 "MIRROR_HASH :=" 变为 "MIRROR_HASH:="
          sed -i -E 's/^([[:space:]]*MIRROR_HASH)[[:space:]]*:=/\1:=/' "$MF"

          # 更新 PKG_MIRROR_HASH（仅首个匹配）
          sed -i -E "0,/^[[:space:]]*PKG_MIRROR_HASH[[:space:]]*:=.*/s//PKG_MIRROR_HASH:=${SHA_PKG}/" "$MF"

          # 仅在 Download/smartdns-webui 段内更新 MIRROR_HASH
          awk -v hash="$SHA_WEBUI" '
            BEGIN{in_webui=0}
            {
              if ($0 ~ /^[[:space:]]*define[[:space:]]+Download\/smartdns-webui/) in_webui=1
              if (in_webui && $0 ~ /^[[:space:]]*MIRROR_HASH[[:space:]]*:=/) {
                sub(/:=.*/," :=" " " hash)
              }
              print
              if (in_webui && $0 ~ /^[[:space:]]*endef[[:space:]]*$/) in_webui=0
            }' "$MF" > "$MF.tmp" && mv "$MF.tmp" "$MF"

          echo "---- DIFF ----"
          git --no-pager diff -- "$MF" || true
          echo "--------------"

          if git diff --quiet -- "$MF"; then
            echo "no_change=true" >> "$GITHUB_OUTPUT"
          else
            echo "no_change=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit & push
        if: ${{ steps.patch.outputs.no_change == 'false' }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Makefile.apk
          git commit -m "chore: update PKG_MIRROR_HASH and webui MIRROR_HASH"
          git push origin HEAD:${{ github.ref_name }}
